[program:ttyd]
priority=35
user=idekube
command=/usr/local/bin/ttyd -p 7681 -i 127.0.0.1 -b /terminal -W -w /home/idekube bash
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=true
environment=HOME="/home/idekube",USER="idekube",SHELL="/bin/bash",PATH="/usr/local/nvm/current:/home/idekube/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",NVM_DIR="/usr/local/nvm"
