[program:turbovnc]
priority=20
user=idekube
directory=/home/idekube
environment=LD_PRELOAD=/usr/lib/libdlfaker.so:/usr/lib/libvglfaker.so
command=/opt/TurboVNC/bin/vncserver :1 -geometry 1280x800 -depth 24 -SecurityTypes None -vgl
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:novnc]
priority=30
directory=/var/lib/novnc
command=bash ./utils/novnc_proxy --vnc localhost:5901 --listen 6081
stopasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:code]
priority=10
command=/usr/local/bin/code-server --bind-addr 0.0.0.0:3000 --auth none --cert false
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
user=idekube
