[program:openclaw]
priority=15
user=idekube
command=openclaw gateway run
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=true
startretries=5
environment=PATH="/usr/local/nvm/current:/home/idekube/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",NVM_DIR="/usr/local/nvm"
