name: Docker Build and Publish

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                arch: [amd64]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Install vcs
              run: sudo apt-get install -y python3-pip && pip3 install vcstool

            - name: Run make publish_all
              run: |
                  make publishx_all
